import requests

# Endpoints for our Model Context Protocol (MCP) server
# In a production environment, these should be loaded from environment variables.
MCP_CALCULATOR_URL = "http://127.0.0.1:8001/calculate"
MCP_SEARCH_URL = "http://127.0.0.1:8001/search"

def research_node(state):
    """
    The Research Node: The "executor" of the system.
    It reads the 'plan' generated by the Planner and calls the external MCP tools.
    """
    plan = state["plan"]

    # 🔹 Execution Path: Calculation
    if plan.startswith("CALCULATE:"):
        # Strip the prefix to get the raw math expression
        expression = plan.replace("CALCULATE:", "").strip()

        try:
            # Send the expression to the MCP FastAPI server
            response = requests.post(
                MCP_CALCULATOR_URL,
                json={"expression": expression}
            )
            result = response.json()

            if result["status"] == "success":
                return {"answer": str(result["result"])}
            else:
                return {"answer": f"Calculation error: {result.get('message')}"}

        except Exception as e:
            return {"answer": f"MCP call failed: {str(e)}"}

    # 🔹 Execution Path: Web Search
    elif plan.startswith("SEARCH:"):
        # Strip the prefix to get the search query
        query = plan.replace("SEARCH:", "").strip()

        try:
            # Perform a GET request to the MCP search endpoint
            response = requests.get(
                MCP_SEARCH_URL,
                params={"query": query}
            )

            result = response.json()

            # Return the search result as the final answer
            return {"answer": result["result"]}

        except Exception as e:
            return {"answer": f"Search failed: {str(e)}"}